### ISSUE TITLE
series group without date

### ISSUE THREAD

**Issue by erdnaxel** [mountainMath/canbank#2]
when i do this

`get_boc_series_group("FSS_2021SPRING_C6")`

I get the error message:

Error: Problem with `mutate()` column `date`.
i `date = parse_boc_date(.data$date)`.
x Column `date` not found in `.data`

I think the problem is at line 280 in the code

**Comment by mountainMath** [comment]
Thanks for flagging. Can you check if this is addressed in the just updated version 0.1.2? Heads-up, there are a couple of changes due to other unrelated data structure issues, the package does not cast the date and value columns to Date and numeric type any more, but creates new `Date` and `Value` column with type-casted values if date and value exist in the data. This was necessary because for some series the data column can't be cast to Date type and value column can't be cast to numeric.

**Comment by erdnaxel** [comment]
It worked! Thanks a bunch...
